#!/bin/sh

echo "--- 🐶 Running pre-commit linting... ---"

npm run lint

if [ $? -ne 0 ]
  echo "--- ❌ ESLint found errors. Fix them and try again. ---"
  exit 1
fi

echo "--- ✅ Everything is fine! Committing... ---"